// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type SetWatchTimeReq struct {
	UserId        int32   `json:"user_id"`
	MovieId       int32   `json:"movie_id"`
	EpisodeId     int32   `json:"episode_id"`
	StartTime     float32 `json:"start_time"`
	EndTime       float32 `json:"end_time"`
	Duration      float32 `json:"duration"`
	LastWatchedAt string  `json:"last_watched_at"`
}

type MessageResp struct {
	Message string `json:"message"`
}
