services:
  scylla:
    image: scylladb/scylla:latest
    container_name: watch_progress_scylla
    ports:
      - "9042:9042"
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "exit"]
      interval: 10s
      timeout: 5s
      retries: 5